name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GPLAY_KEYSTORE: ${{ secrets.GPLAY_KEYSTORE }}
      GPLAY_KEY_ALIAS: ${{ secrets.GPLAY_KEY_ALIAS }}
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
      GPLAY_KEY_PASSWORD: ${{ secrets.GPLAY_KEY_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre-new
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-pojav

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre-21
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-pojav

      - name: Make language updater executable
        run: chmod +x ./scripts/languagelist_updater.sh

      - name: Run language list updater
        run: |
          ./scripts/languagelist_updater.sh || echo "Language list update failed, continuing..."

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore $GPLAY_KEYSTORE \
          -storepass $GPLAY_KEYSTORE_PASSWORD \
          -keypass $GPLAY_KEY_PASSWORD \
          app/build/outputs/apk/release/app-release-unsigned.apk $GPLAY_KEY_ALIAS

      - name: Align APK
        run: |
          ${ANDROID_HOME}/build-tools/30.0.3/zipalign -v 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app/build/outputs/apk/release/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Finalize Build
        run: echo "Build process completed."
