name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      GRADLE_USER_HOME: /home/runner/.gradle

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1
          cache-read-only: false

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: List Gradle Tasks
        run: ./gradlew tasks --all

      - name: Make language updater executable
        run: chmod +x ./scripts/languagelist_updater.sh

      - name: Run language list updater
        run: |
          ./scripts/languagelist_updater.sh || echo "Language list update failed, continuing..."

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --no-daemon
        working-directory: app  # Replace 'app' with the correct module if necessary
